// Comprehensive international data for the restaurant platform.
// Covers all world countries (ISO 3166-1 alpha-2), currencies, and major languages.

export interface Country {
  code: string;
  name: string;
  currency: string;
  flag: string;
  dialCode: string;
}

export interface Currency {
  code: string;
  name: string;
  symbol: string;
  rate: number;
}

export interface Language {
  code: string;
  name: string;
  nativeName: string;
  flag: string;
}

// ---------------------------------------------------------------------------
// COUNTRIES — all UN member states + observers and widely-recognized territories.
// code: ISO 3166-1 alpha-2
// currency: primary local currency ISO 4217 code
// flag: emoji flag (regional indicator pair)
// dialCode: ITU-T E.164 country calling code (without "+")
// ---------------------------------------------------------------------------
export const COUNTRIES: Country[] = [
  { code: "AD", name: "Andorra", currency: "EUR", flag: "🇦🇩", dialCode: "376" },
  { code: "AE", name: "United Arab Emirates", currency: "AED", flag: "🇦🇪", dialCode: "971" },
  { code: "AF", name: "Afghanistan", currency: "AFN", flag: "🇦🇫", dialCode: "93" },
  { code: "AG", name: "Antigua and Barbuda", currency: "XCD", flag: "🇦🇬", dialCode: "1" },
  { code: "AI", name: "Anguilla", currency: "XCD", flag: "🇦🇮", dialCode: "1" },
  { code: "AL", name: "Albania", currency: "ALL", flag: "🇦🇱", dialCode: "355" },
  { code: "AM", name: "Armenia", currency: "AMD", flag: "🇦🇲", dialCode: "374" },
  { code: "AO", name: "Angola", currency: "AOA", flag: "🇦🇴", dialCode: "244" },
  { code: "AQ", name: "Antarctica", currency: "USD", flag: "🇦🇶", dialCode: "672" },
  { code: "AR", name: "Argentina", currency: "ARS", flag: "🇦🇷", dialCode: "54" },
  { code: "AS", name: "American Samoa", currency: "USD", flag: "🇦🇸", dialCode: "1" },
  { code: "AT", name: "Austria", currency: "EUR", flag: "🇦🇹", dialCode: "43" },
  { code: "AU", name: "Australia", currency: "AUD", flag: "🇦🇺", dialCode: "61" },
  { code: "AW", name: "Aruba", currency: "AWG", flag: "🇦🇼", dialCode: "297" },
  { code: "AX", name: "Åland Islands", currency: "EUR", flag: "🇦🇽", dialCode: "358" },
  { code: "AZ", name: "Azerbaijan", currency: "AZN", flag: "🇦🇿", dialCode: "994" },
  { code: "BA", name: "Bosnia and Herzegovina", currency: "BAM", flag: "🇧🇦", dialCode: "387" },
  { code: "BB", name: "Barbados", currency: "BBD", flag: "🇧🇧", dialCode: "1" },
  { code: "BD", name: "Bangladesh", currency: "BDT", flag: "🇧🇩", dialCode: "880" },
  { code: "BE", name: "Belgium", currency: "EUR", flag: "🇧🇪", dialCode: "32" },
  { code: "BF", name: "Burkina Faso", currency: "XOF", flag: "🇧🇫", dialCode: "226" },
  { code: "BG", name: "Bulgaria", currency: "BGN", flag: "🇧🇬", dialCode: "359" },
  { code: "BH", name: "Bahrain", currency: "BHD", flag: "🇧🇭", dialCode: "973" },
  { code: "BI", name: "Burundi", currency: "BIF", flag: "🇧🇮", dialCode: "257" },
  { code: "BJ", name: "Benin", currency: "XOF", flag: "🇧🇯", dialCode: "229" },
  { code: "BL", name: "Saint Barthélemy", currency: "EUR", flag: "🇧🇱", dialCode: "590" },
  { code: "BM", name: "Bermuda", currency: "BMD", flag: "🇧🇲", dialCode: "1" },
  { code: "BN", name: "Brunei Darussalam", currency: "BND", flag: "🇧🇳", dialCode: "673" },
  { code: "BO", name: "Bolivia", currency: "BOB", flag: "🇧🇴", dialCode: "591" },
  { code: "BQ", name: "Bonaire, Sint Eustatius and Saba", currency: "USD", flag: "🇧🇶", dialCode: "599" },
  { code: "BR", name: "Brazil", currency: "BRL", flag: "🇧🇷", dialCode: "55" },
  { code: "BS", name: "Bahamas", currency: "BSD", flag: "🇧🇸", dialCode: "1" },
  { code: "BT", name: "Bhutan", currency: "BTN", flag: "🇧🇹", dialCode: "975" },
  { code: "BV", name: "Bouvet Island", currency: "NOK", flag: "🇧🇻", dialCode: "47" },
  { code: "BW", name: "Botswana", currency: "BWP", flag: "🇧🇼", dialCode: "267" },
  { code: "BY", name: "Belarus", currency: "BYN", flag: "🇧🇾", dialCode: "375" },
  { code: "BZ", name: "Belize", currency: "BZD", flag: "🇧🇿", dialCode: "501" },
  { code: "CA", name: "Canada", currency: "CAD", flag: "🇨🇦", dialCode: "1" },
  { code: "CC", name: "Cocos (Keeling) Islands", currency: "AUD", flag: "🇨🇨", dialCode: "61" },
  { code: "CD", name: "Congo, Democratic Republic of the", currency: "CDF", flag: "🇨🇩", dialCode: "243" },
  { code: "CF", name: "Central African Republic", currency: "XAF", flag: "🇨🇫", dialCode: "236" },
  { code: "CG", name: "Congo", currency: "XAF", flag: "🇨🇬", dialCode: "242" },
  { code: "CH", name: "Switzerland", currency: "CHF", flag: "🇨🇭", dialCode: "41" },
  { code: "CI", name: "Côte d'Ivoire", currency: "XOF", flag: "🇨🇮", dialCode: "225" },
  { code: "CK", name: "Cook Islands", currency: "NZD", flag: "🇨🇰", dialCode: "682" },
  { code: "CL", name: "Chile", currency: "CLP", flag: "🇨🇱", dialCode: "56" },
  { code: "CM", name: "Cameroon", currency: "XAF", flag: "🇨🇲", dialCode: "237" },
  { code: "CN", name: "China", currency: "CNY", flag: "🇨🇳", dialCode: "86" },
  { code: "CO", name: "Colombia", currency: "COP", flag: "🇨🇴", dialCode: "57" },
  { code: "CR", name: "Costa Rica", currency: "CRC", flag: "🇨🇷", dialCode: "506" },
  { code: "CU", name: "Cuba", currency: "CUP", flag: "🇨🇺", dialCode: "53" },
  { code: "CV", name: "Cabo Verde", currency: "CVE", flag: "🇨🇻", dialCode: "238" },
  { code: "CW", name: "Curaçao", currency: "ANG", flag: "🇨🇼", dialCode: "599" },
  { code: "CX", name: "Christmas Island", currency: "AUD", flag: "🇨🇽", dialCode: "61" },
  { code: "CY", name: "Cyprus", currency: "EUR", flag: "🇨🇾", dialCode: "357" },
  { code: "CZ", name: "Czechia", currency: "CZK", flag: "🇨🇿", dialCode: "420" },
  { code: "DE", name: "Germany", currency: "EUR", flag: "🇩🇪", dialCode: "49" },
  { code: "DJ", name: "Djibouti", currency: "DJF", flag: "🇩🇯", dialCode: "253" },
  { code: "DK", name: "Denmark", currency: "DKK", flag: "🇩🇰", dialCode: "45" },
  { code: "DM", name: "Dominica", currency: "XCD", flag: "🇩🇲", dialCode: "1" },
  { code: "DO", name: "Dominican Republic", currency: "DOP", flag: "🇩🇴", dialCode: "1" },
  { code: "DZ", name: "Algeria", currency: "DZD", flag: "🇩🇿", dialCode: "213" },
  { code: "EC", name: "Ecuador", currency: "USD", flag: "🇪🇨", dialCode: "593" },
  { code: "EE", name: "Estonia", currency: "EUR", flag: "🇪🇪", dialCode: "372" },
  { code: "EG", name: "Egypt", currency: "EGP", flag: "🇪🇬", dialCode: "20" },
  { code: "EH", name: "Western Sahara", currency: "MAD", flag: "🇪🇭", dialCode: "212" },
  { code: "ER", name: "Eritrea", currency: "ERN", flag: "🇪🇷", dialCode: "291" },
  { code: "ES", name: "Spain", currency: "EUR", flag: "🇪🇸", dialCode: "34" },
  { code: "ET", name: "Ethiopia", currency: "ETB", flag: "🇪🇹", dialCode: "251" },
  { code: "FI", name: "Finland", currency: "EUR", flag: "🇫🇮", dialCode: "358" },
  { code: "FJ", name: "Fiji", currency: "FJD", flag: "🇫🇯", dialCode: "679" },
  { code: "FK", name: "Falkland Islands (Malvinas)", currency: "FKP", flag: "🇫🇰", dialCode: "500" },
  { code: "FM", name: "Micronesia, Federated States of", currency: "USD", flag: "🇫🇲", dialCode: "691" },
  { code: "FO", name: "Faroe Islands", currency: "DKK", flag: "🇫🇴", dialCode: "298" },
  { code: "FR", name: "France", currency: "EUR", flag: "🇫🇷", dialCode: "33" },
  { code: "GA", name: "Gabon", currency: "XAF", flag: "🇬🇦", dialCode: "241" },
  { code: "GB", name: "United Kingdom", currency: "GBP", flag: "🇬🇧", dialCode: "44" },
  { code: "GD", name: "Grenada", currency: "XCD", flag: "🇬🇩", dialCode: "1" },
  { code: "GE", name: "Georgia", currency: "GEL", flag: "🇬🇪", dialCode: "995" },
  { code: "GF", name: "French Guiana", currency: "EUR", flag: "🇬🇫", dialCode: "594" },
  { code: "GG", name: "Guernsey", currency: "GBP", flag: "🇬🇬", dialCode: "44" },
  { code: "GH", name: "Ghana", currency: "GHS", flag: "🇬🇭", dialCode: "233" },
  { code: "GI", name: "Gibraltar", currency: "GIP", flag: "🇬🇮", dialCode: "350" },
  { code: "GL", name: "Greenland", currency: "DKK", flag: "🇬🇱", dialCode: "299" },
  { code: "GM", name: "Gambia", currency: "GMD", flag: "🇬🇲", dialCode: "220" },
  { code: "GN", name: "Guinea", currency: "GNF", flag: "🇬🇳", dialCode: "224" },
  { code: "GP", name: "Guadeloupe", currency: "EUR", flag: "🇬🇵", dialCode: "590" },
  { code: "GQ", name: "Equatorial Guinea", currency: "XAF", flag: "🇬🇶", dialCode: "240" },
  { code: "GR", name: "Greece", currency: "EUR", flag: "🇬🇷", dialCode: "30" },
  { code: "GS", name: "South Georgia and the South Sandwich Islands", currency: "GBP", flag: "🇬🇸", dialCode: "500" },
  { code: "GT", name: "Guatemala", currency: "GTQ", flag: "🇬🇹", dialCode: "502" },
  { code: "GU", name: "Guam", currency: "USD", flag: "🇬🇺", dialCode: "1" },
  { code: "GW", name: "Guinea-Bissau", currency: "XOF", flag: "🇬🇼", dialCode: "245" },
  { code: "GY", name: "Guyana", currency: "GYD", flag: "🇬🇾", dialCode: "592" },
  { code: "HK", name: "Hong Kong", currency: "HKD", flag: "🇭🇰", dialCode: "852" },
  { code: "HM", name: "Heard Island and McDonald Islands", currency: "AUD", flag: "🇭🇲", dialCode: "61" },
  { code: "HN", name: "Honduras", currency: "HNL", flag: "🇭🇳", dialCode: "504" },
  { code: "HR", name: "Croatia", currency: "EUR", flag: "🇭🇷", dialCode: "385" },
  { code: "HT", name: "Haiti", currency: "HTG", flag: "🇭🇹", dialCode: "509" },
  { code: "HU", name: "Hungary", currency: "HUF", flag: "🇭🇺", dialCode: "36" },
  { code: "ID", name: "Indonesia", currency: "IDR", flag: "🇮🇩", dialCode: "62" },
  { code: "IE", name: "Ireland", currency: "EUR", flag: "🇮🇪", dialCode: "353" },
  { code: "IL", name: "Israel", currency: "ILS", flag: "🇮🇱", dialCode: "972" },
  { code: "IM", name: "Isle of Man", currency: "GBP", flag: "🇮🇲", dialCode: "44" },
  { code: "IN", name: "India", currency: "INR", flag: "🇮🇳", dialCode: "91" },
  { code: "IO", name: "British Indian Ocean Territory", currency: "USD", flag: "🇮🇴", dialCode: "246" },
  { code: "IQ", name: "Iraq", currency: "IQD", flag: "🇮🇶", dialCode: "964" },
  { code: "IR", name: "Iran, Islamic Republic of", currency: "IRR", flag: "🇮🇷", dialCode: "98" },
  { code: "IS", name: "Iceland", currency: "ISK", flag: "🇮🇸", dialCode: "354" },
  { code: "IT", name: "Italy", currency: "EUR", flag: "🇮🇹", dialCode: "39" },
  { code: "JE", name: "Jersey", currency: "GBP", flag: "🇯🇪", dialCode: "44" },
  { code: "JM", name: "Jamaica", currency: "JMD", flag: "🇯🇲", dialCode: "1" },
  { code: "JO", name: "Jordan", currency: "JOD", flag: "🇯🇴", dialCode: "962" },
  { code: "JP", name: "Japan", currency: "JPY", flag: "🇯🇵", dialCode: "81" },
  { code: "KE", name: "Kenya", currency: "KES", flag: "🇰🇪", dialCode: "254" },
  { code: "KG", name: "Kyrgyzstan", currency: "KGS", flag: "🇰🇬", dialCode: "996" },
  { code: "KH", name: "Cambodia", currency: "KHR", flag: "🇰🇭", dialCode: "855" },
  { code: "KI", name: "Kiribati", currency: "AUD", flag: "🇰🇮", dialCode: "686" },
  { code: "KM", name: "Comoros", currency: "KMF", flag: "🇰🇲", dialCode: "269" },
  { code: "KN", name: "Saint Kitts and Nevis", currency: "XCD", flag: "🇰🇳", dialCode: "1" },
  { code: "KP", name: "Korea, Democratic People's Republic of", currency: "KPW", flag: "🇰🇵", dialCode: "850" },
  { code: "KR", name: "Korea, Republic of", currency: "KRW", flag: "🇰🇷", dialCode: "82" },
  { code: "KW", name: "Kuwait", currency: "KWD", flag: "🇰🇼", dialCode: "965" },
  { code: "KY", name: "Cayman Islands", currency: "KYD", flag: "🇰🇾", dialCode: "1" },
  { code: "KZ", name: "Kazakhstan", currency: "KZT", flag: "🇰🇿", dialCode: "7" },
  { code: "LA", name: "Lao People's Democratic Republic", currency: "LAK", flag: "🇱🇦", dialCode: "856" },
  { code: "LB", name: "Lebanon", currency: "LBP", flag: "🇱🇧", dialCode: "961" },
  { code: "LC", name: "Saint Lucia", currency: "XCD", flag: "🇱🇨", dialCode: "1" },
  { code: "LI", name: "Liechtenstein", currency: "CHF", flag: "🇱🇮", dialCode: "423" },
  { code: "LK", name: "Sri Lanka", currency: "LKR", flag: "🇱🇰", dialCode: "94" },
  { code: "LR", name: "Liberia", currency: "LRD", flag: "🇱🇷", dialCode: "231" },
  { code: "LS", name: "Lesotho", currency: "LSL", flag: "🇱🇸", dialCode: "266" },
  { code: "LT", name: "Lithuania", currency: "EUR", flag: "🇱🇹", dialCode: "370" },
  { code: "LU", name: "Luxembourg", currency: "EUR", flag: "🇱🇺", dialCode: "352" },
  { code: "LV", name: "Latvia", currency: "EUR", flag: "🇱🇻", dialCode: "371" },
  { code: "LY", name: "Libya", currency: "LYD", flag: "🇱🇾", dialCode: "218" },
  { code: "MA", name: "Morocco", currency: "MAD", flag: "🇲🇦", dialCode: "212" },
  { code: "MC", name: "Monaco", currency: "EUR", flag: "🇲🇨", dialCode: "377" },
  { code: "MD", name: "Moldova, Republic of", currency: "MDL", flag: "🇲🇩", dialCode: "373" },
  { code: "ME", name: "Montenegro", currency: "EUR", flag: "🇲🇪", dialCode: "382" },
  { code: "MF", name: "Saint Martin (French part)", currency: "EUR", flag: "🇲🇫", dialCode: "590" },
  { code: "MG", name: "Madagascar", currency: "MGA", flag: "🇲🇬", dialCode: "261" },
  { code: "MH", name: "Marshall Islands", currency: "USD", flag: "🇲🇭", dialCode: "692" },
  { code: "MK", name: "North Macedonia", currency: "MKD", flag: "🇲🇰", dialCode: "389" },
  { code: "ML", name: "Mali", currency: "XOF", flag: "🇲🇱", dialCode: "223" },
  { code: "MM", name: "Myanmar", currency: "MMK", flag: "🇲🇲", dialCode: "95" },
  { code: "MN", name: "Mongolia", currency: "MNT", flag: "🇲🇳", dialCode: "976" },
  { code: "MO", name: "Macao", currency: "MOP", flag: "🇲🇴", dialCode: "853" },
  { code: "MP", name: "Northern Mariana Islands", currency: "USD", flag: "🇲🇵", dialCode: "1" },
  { code: "MQ", name: "Martinique", currency: "EUR", flag: "🇲🇶", dialCode: "596" },
  { code: "MR", name: "Mauritania", currency: "MRU", flag: "🇲🇷", dialCode: "222" },
  { code: "MS", name: "Montserrat", currency: "XCD", flag: "🇲🇸", dialCode: "1" },
  { code: "MT", name: "Malta", currency: "EUR", flag: "🇲🇹", dialCode: "356" },
  { code: "MU", name: "Mauritius", currency: "MUR", flag: "🇲🇺", dialCode: "230" },
  { code: "MV", name: "Maldives", currency: "MVR", flag: "🇲🇻", dialCode: "960" },
  { code: "MW", name: "Malawi", currency: "MWK", flag: "🇲🇼", dialCode: "265" },
  { code: "MX", name: "Mexico", currency: "MXN", flag: "🇲🇽", dialCode: "52" },
  { code: "MY", name: "Malaysia", currency: "MYR", flag: "🇲🇾", dialCode: "60" },
  { code: "MZ", name: "Mozambique", currency: "MZN", flag: "🇲🇿", dialCode: "258" },
  { code: "NA", name: "Namibia", currency: "NAD", flag: "🇳🇦", dialCode: "264" },
  { code: "NC", name: "New Caledonia", currency: "XPF", flag: "🇳🇨", dialCode: "687" },
  { code: "NE", name: "Niger", currency: "XOF", flag: "🇳🇪", dialCode: "227" },
  { code: "NF", name: "Norfolk Island", currency: "AUD", flag: "🇳🇫", dialCode: "672" },
  { code: "NG", name: "Nigeria", currency: "NGN", flag: "🇳🇬", dialCode: "234" },
  { code: "NI", name: "Nicaragua", currency: "NIO", flag: "🇳🇮", dialCode: "505" },
  { code: "NL", name: "Netherlands", currency: "EUR", flag: "🇳🇱", dialCode: "31" },
  { code: "NO", name: "Norway", currency: "NOK", flag: "🇳🇴", dialCode: "47" },
  { code: "NP", name: "Nepal", currency: "NPR", flag: "🇳🇵", dialCode: "977" },
  { code: "NR", name: "Nauru", currency: "AUD", flag: "🇳🇷", dialCode: "674" },
  { code: "NU", name: "Niue", currency: "NZD", flag: "🇳🇺", dialCode: "683" },
  { code: "NZ", name: "New Zealand", currency: "NZD", flag: "🇳🇿", dialCode: "64" },
  { code: "OM", name: "Oman", currency: "OMR", flag: "🇴🇲", dialCode: "968" },
  { code: "PA", name: "Panama", currency: "PAB", flag: "🇵🇦", dialCode: "507" },
  { code: "PE", name: "Peru", currency: "PEN", flag: "🇵🇪", dialCode: "51" },
  { code: "PF", name: "French Polynesia", currency: "XPF", flag: "🇵🇫", dialCode: "689" },
  { code: "PG", name: "Papua New Guinea", currency: "PGK", flag: "🇵🇬", dialCode: "675" },
  { code: "PH", name: "Philippines", currency: "PHP", flag: "🇵🇭", dialCode: "63" },
  { code: "PK", name: "Pakistan", currency: "PKR", flag: "🇵🇰", dialCode: "92" },
  { code: "PL", name: "Poland", currency: "PLN", flag: "🇵🇱", dialCode: "48" },
  { code: "PM", name: "Saint Pierre and Miquelon", currency: "EUR", flag: "🇵🇲", dialCode: "508" },
  { code: "PN", name: "Pitcairn", currency: "NZD", flag: "🇵🇳", dialCode: "64" },
  { code: "PR", name: "Puerto Rico", currency: "USD", flag: "🇵🇷", dialCode: "1" },
  { code: "PS", name: "Palestine, State of", currency: "ILS", flag: "🇵🇸", dialCode: "970" },
  { code: "PT", name: "Portugal", currency: "EUR", flag: "🇵🇹", dialCode: "351" },
  { code: "PW", name: "Palau", currency: "USD", flag: "🇵🇼", dialCode: "680" },
  { code: "PY", name: "Paraguay", currency: "PYG", flag: "🇵🇾", dialCode: "595" },
  { code: "QA", name: "Qatar", currency: "QAR", flag: "🇶🇦", dialCode: "974" },
  { code: "RE", name: "Réunion", currency: "EUR", flag: "🇷🇪", dialCode: "262" },
  { code: "RO", name: "Romania", currency: "RON", flag: "🇷🇴", dialCode: "40" },
  { code: "RS", name: "Serbia", currency: "RSD", flag: "🇷🇸", dialCode: "381" },
  { code: "RU", name: "Russian Federation", currency: "RUB", flag: "🇷🇺", dialCode: "7" },
  { code: "RW", name: "Rwanda", currency: "RWF", flag: "🇷🇼", dialCode: "250" },
  { code: "SA", name: "Saudi Arabia", currency: "SAR", flag: "🇸🇦", dialCode: "966" },
  { code: "SB", name: "Solomon Islands", currency: "SBD", flag: "🇸🇧", dialCode: "677" },
  { code: "SC", name: "Seychelles", currency: "SCR", flag: "🇸🇨", dialCode: "248" },
  { code: "SD", name: "Sudan", currency: "SDG", flag: "🇸🇩", dialCode: "249" },
  { code: "SE", name: "Sweden", currency: "SEK", flag: "🇸🇪", dialCode: "46" },
  { code: "SG", name: "Singapore", currency: "SGD", flag: "🇸🇬", dialCode: "65" },
  { code: "SH", name: "Saint Helena, Ascension and Tristan da Cunha", currency: "SHP", flag: "🇸🇭", dialCode: "290" },
  { code: "SI", name: "Slovenia", currency: "EUR", flag: "🇸🇮", dialCode: "386" },
  { code: "SJ", name: "Svalbard and Jan Mayen", currency: "NOK", flag: "🇸🇯", dialCode: "47" },
  { code: "SK", name: "Slovakia", currency: "EUR", flag: "🇸🇰", dialCode: "421" },
  { code: "SL", name: "Sierra Leone", currency: "SLL", flag: "🇸🇱", dialCode: "232" },
  { code: "SM", name: "San Marino", currency: "EUR", flag: "🇸🇲", dialCode: "378" },
  { code: "SN", name: "Senegal", currency: "XOF", flag: "🇸🇳", dialCode: "221" },
  { code: "SO", name: "Somalia", currency: "SOS", flag: "🇸🇴", dialCode: "252" },
  { code: "SR", name: "Suriname", currency: "SRD", flag: "🇸🇷", dialCode: "597" },
  { code: "SS", name: "South Sudan", currency: "SSP", flag: "🇸🇸", dialCode: "211" },
  { code: "ST", name: "Sao Tome and Principe", currency: "STN", flag: "🇸🇹", dialCode: "239" },
  { code: "SV", name: "El Salvador", currency: "USD", flag: "🇸🇻", dialCode: "503" },
  { code: "SX", name: "Sint Maarten (Dutch part)", currency: "ANG", flag: "🇸🇽", dialCode: "1" },
  { code: "SY", name: "Syrian Arab Republic", currency: "SYP", flag: "🇸🇾", dialCode: "963" },
  { code: "SZ", name: "Eswatini", currency: "SZL", flag: "🇸🇿", dialCode: "268" },
  { code: "TC", name: "Turks and Caicos Islands", currency: "USD", flag: "🇹🇨", dialCode: "1" },
  { code: "TD", name: "Chad", currency: "XAF", flag: "🇹🇩", dialCode: "235" },
  { code: "TF", name: "French Southern Territories", currency: "EUR", flag: "🇹🇫", dialCode: "262" },
  { code: "TG", name: "Togo", currency: "XOF", flag: "🇹🇬", dialCode: "228" },
  { code: "TH", name: "Thailand", currency: "THB", flag: "🇹🇭", dialCode: "66" },
  { code: "TJ", name: "Tajikistan", currency: "TJS", flag: "🇹🇯", dialCode: "992" },
  { code: "TK", name: "Tokelau", currency: "NZD", flag: "🇹🇰", dialCode: "690" },
  { code: "TL", name: "Timor-Leste", currency: "USD", flag: "🇹🇱", dialCode: "670" },
  { code: "TM", name: "Turkmenistan", currency: "TMT", flag: "🇹🇲", dialCode: "993" },
  { code: "TN", name: "Tunisia", currency: "TND", flag: "🇹🇳", dialCode: "216" },
  { code: "TO", name: "Tonga", currency: "TOP", flag: "🇹🇴", dialCode: "676" },
  { code: "TR", name: "Turkey", currency: "TRY", flag: "🇹🇷", dialCode: "90" },
  { code: "TT", name: "Trinidad and Tobago", currency: "TTD", flag: "🇹🇹", dialCode: "1" },
  { code: "TV", name: "Tuvalu", currency: "AUD", flag: "🇹🇻", dialCode: "688" },
  { code: "TW", name: "Taiwan, Province of China", currency: "TWD", flag: "🇹🇼", dialCode: "886" },
  { code: "TZ", name: "Tanzania, United Republic of", currency: "TZS", flag: "🇹🇿", dialCode: "255" },
  { code: "UA", name: "Ukraine", currency: "UAH", flag: "🇺🇦", dialCode: "380" },
  { code: "UG", name: "Uganda", currency: "UGX", flag: "🇺🇬", dialCode: "256" },
  { code: "UM", name: "United States Minor Outlying Islands", currency: "USD", flag: "🇺🇲", dialCode: "1" },
  { code: "US", name: "United States", currency: "USD", flag: "🇺🇸", dialCode: "1" },
  { code: "UY", name: "Uruguay", currency: "UYU", flag: "🇺🇾", dialCode: "598" },
  { code: "UZ", name: "Uzbekistan", currency: "UZS", flag: "🇺🇿", dialCode: "998" },
  { code: "VA", name: "Holy See (Vatican City State)", currency: "EUR", flag: "🇻🇦", dialCode: "39" },
  { code: "VC", name: "Saint Vincent and the Grenadines", currency: "XCD", flag: "🇻🇨", dialCode: "1" },
  { code: "VE", name: "Venezuela, Bolivarian Republic of", currency: "VES", flag: "🇻🇪", dialCode: "58" },
  { code: "VG", name: "Virgin Islands, British", currency: "USD", flag: "🇻🇬", dialCode: "1" },
  { code: "VI", name: "Virgin Islands, U.S.", currency: "USD", flag: "🇻🇮", dialCode: "1" },
  { code: "VN", name: "Vietnam", currency: "VND", flag: "🇻🇳", dialCode: "84" },
  { code: "VU", name: "Vanuatu", currency: "VUV", flag: "🇻🇺", dialCode: "678" },
  { code: "WF", name: "Wallis and Futuna", currency: "XPF", flag: "🇼🇫", dialCode: "681" },
  { code: "WS", name: "Samoa", currency: "WST", flag: "🇼🇸", dialCode: "685" },
  { code: "YE", name: "Yemen", currency: "YER", flag: "🇾🇪", dialCode: "967" },
  { code: "YT", name: "Mayotte", currency: "EUR", flag: "🇾🇹", dialCode: "262" },
  { code: "ZA", name: "South Africa", currency: "ZAR", flag: "🇿🇦", dialCode: "27" },
  { code: "ZM", name: "Zambia", currency: "ZMW", flag: "🇿🇲", dialCode: "260" },
  { code: "ZW", name: "Zimbabwe", currency: "ZWL", flag: "🇿🇼", dialCode: "263" },
  { code: "XK", name: "Kosovo", currency: "EUR", flag: "🇽🇰", dialCode: "383" },
];

// ---------------------------------------------------------------------------
// CURRENCIES — world currencies with symbols and approximate USD exchange rates.
// rate: 1 USD = rate units of this currency (approximate, for display/reference only).
// ---------------------------------------------------------------------------
export const CURRENCIES: Currency[] = [
  // Major reserve currencies
  { code: "USD", name: "US Dollar", symbol: "$", rate: 1 },
  { code: "EUR", name: "Euro", symbol: "€", rate: 0.92 },
  { code: "GBP", name: "British Pound Sterling", symbol: "£", rate: 0.79 },
  { code: "JPY", name: "Japanese Yen", symbol: "¥", rate: 156 },
  { code: "CNY", name: "Chinese Yuan", symbol: "¥", rate: 7.24 },
  { code: "CHF", name: "Swiss Franc", symbol: "CHF", rate: 0.9 },
  { code: "CAD", name: "Canadian Dollar", symbol: "C$", rate: 1.37 },
  { code: "MXN", name: "Mexican Peso", symbol: "$", rate: 17.8 },
  { code: "AUD", name: "Australian Dollar", symbol: "A$", rate: 1.52 },
  // East & Southeast Asia
  { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$", rate: 7.81 },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$", rate: 1.35 },
  { code: "TWD", name: "Taiwan Dollar", symbol: "NT$", rate: 32 },
  { code: "KRW", name: "South Korean Won", symbol: "₩", rate: 1370 },
  { code: "KPW", name: "North Korean Won", symbol: "₩", rate: 900 },
  { code: "MOP", name: "Macanese Pataca", symbol: "MOP$", rate: 8.05 },
  { code: "MNT", name: "Mongolian Tugrik", symbol: "₮", rate: 3380 },
  { code: "THB", name: "Thai Baht", symbol: "฿", rate: 36 },
  { code: "VND", name: "Vietnamese Dong", symbol: "₫", rate: 25400 },
  { code: "KHR", name: "Cambodian Riel", symbol: "៛", rate: 4100 },
  { code: "LAK", name: "Lao Kip", symbol: "₭", rate: 22000 },
  { code: "MMK", name: "Myanmar Kyat", symbol: "K", rate: 2100 },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp", rate: 16200 },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM", rate: 4.7 },
  { code: "PHP", name: "Philippine Peso", symbol: "₱", rate: 58 },
  { code: "BND", name: "Brunei Dollar", symbol: "B$", rate: 1.35 },
  // South Asia
  { code: "INR", name: "Indian Rupee", symbol: "₹", rate: 83 },
  { code: "PKR", name: "Pakistani Rupee", symbol: "₨", rate: 278 },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "৳", rate: 117 },
  { code: "LKR", name: "Sri Lankan Rupee", symbol: "₨", rate: 300 },
  { code: "NPR", name: "Nepalese Rupee", symbol: "₨", rate: 133 },
  { code: "MVR", name: "Maldivian Rufiyaa", symbol: "Rf", rate: 15.4 },
  { code: "BTN", name: "Bhutanese Ngultrum", symbol: "Nu.", rate: 83 },
  { code: "AFN", name: "Afghan Afghani", symbol: "؋", rate: 70 },
  // Central Asia
  { code: "KZT", name: "Kazakhstani Tenge", symbol: "₸", rate: 460 },
  { code: "UZS", name: "Uzbekistani Som", symbol: "so'm", rate: 12700 },
  { code: "KGS", name: "Kyrgyzstani Som", symbol: "с", rate: 89 },
  { code: "TJS", name: "Tajikistani Somoni", symbol: "ЅМ", rate: 10.9 },
  { code: "TMT", name: "Turkmenistani Manat", symbol: "m", rate: 3.5 },
  // Middle East & Western Asia
  { code: "AED", name: "UAE Dirham", symbol: "د.إ", rate: 3.67 },
  { code: "SAR", name: "Saudi Riyal", symbol: "﷼", rate: 3.75 },
  { code: "QAR", name: "Qatari Riyal", symbol: "﷼", rate: 3.64 },
  { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك", rate: 0.31 },
  { code: "BHD", name: "Bahraini Dinar", symbol: "د.ب", rate: 0.376 },
  { code: "OMR", name: "Omani Rial", symbol: "﷼", rate: 0.385 },
  { code: "JOD", name: "Jordanian Dinar", symbol: "د.ا", rate: 0.709 },
  { code: "ILS", name: "Israeli New Shekel", symbol: "₪", rate: 3.7 },
  { code: "LBP", name: "Lebanese Pound", symbol: "ل.ل", rate: 89500 },
  { code: "SYP", name: "Syrian Pound", symbol: "£S", rate: 13000 },
  { code: "IQD", name: "Iraqi Dinar", symbol: "ع.د", rate: 1310 },
  { code: "IRR", name: "Iranian Rial", symbol: "﷼", rate: 42000 },
  { code: "YER", name: "Yemeni Rial", symbol: "﷼", rate: 570 },
  // Caucasus
  { code: "AZN", name: "Azerbaijani Manat", symbol: "₼", rate: 1.7 },
  { code: "GEL", name: "Georgian Lari", symbol: "₾", rate: 2.72 },
  { code: "AMD", name: "Armenian Dram", symbol: "֏", rate: 388 },
  // Eastern Europe & Baltics
  { code: "RUB", name: "Russian Ruble", symbol: "₽", rate: 92 },
  { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴", rate: 40 },
  { code: "BYN", name: "Belarusian Ruble", symbol: "Br", rate: 3.2 },
  { code: "MDL", name: "Moldovan Leu", symbol: "L", rate: 17.8 },
  { code: "RON", name: "Romanian Leu", symbol: "lei", rate: 4.56 },
  { code: "BGN", name: "Bulgarian Lev", symbol: "лв", rate: 1.8 },
  { code: "TRY", name: "Turkish Lira", symbol: "₺", rate: 32 },
  // Balkans
  { code: "RSD", name: "Serbian Dinar", symbol: "дин", rate: 108 },
  { code: "MKD", name: "Macedonian Denar", symbol: "ден", rate: 57 },
  { code: "ALL", name: "Albanian Lek", symbol: "L", rate: 93 },
  { code: "BAM", name: "Bosnia-Herzegovina Mark", symbol: "KM", rate: 1.8 },
  { code: "HRK", name: "Croatian Kuna", symbol: "kn", rate: 6.95 },
  // Nordic & Northern Europe
  { code: "SEK", name: "Swedish Krona", symbol: "kr", rate: 10.7 },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr", rate: 10.8 },
  { code: "DKK", name: "Danish Krone", symbol: "kr", rate: 6.86 },
  { code: "ISK", name: "Icelandic Króna", symbol: "kr", rate: 140 },
  { code: "PLN", name: "Polish Zloty", symbol: "zł", rate: 4.0 },
  { code: "CZK", name: "Czech Koruna", symbol: "Kč", rate: 23.2 },
  { code: "HUF", name: "Hungarian Forint", symbol: "Ft", rate: 360 },
  // Oceania
  { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$", rate: 1.65 },
  { code: "FJD", name: "Fijian Dollar", symbol: "FJ$", rate: 2.25 },
  { code: "PGK", name: "Papua New Guinean Kina", symbol: "K", rate: 3.8 },
  { code: "SBD", name: "Solomon Islands Dollar", symbol: "SI$", rate: 8.4 },
  { code: "VUV", name: "Vanuatu Vatu", symbol: "Vt", rate: 119 },
  { code: "WST", name: "Samoan Tala", symbol: "T", rate: 2.7 },
  { code: "TOP", name: "Tongan Pa'anga", symbol: "T$", rate: 2.35 },
  // Southern Africa
  { code: "ZAR", name: "South African Rand", symbol: "R", rate: 18.5 },
  { code: "NAD", name: "Namibian Dollar", symbol: "N$", rate: 18.5 },
  { code: "BWP", name: "Botswana Pula", symbol: "P", rate: 13.6 },
  { code: "LSL", name: "Lesotho Loti", symbol: "L", rate: 18.5 },
  { code: "SZL", name: "Eswatini Lilangeni", symbol: "L", rate: 18.5 },
  { code: "ZMW", name: "Zambian Kwacha", symbol: "ZK", rate: 25 },
  { code: "ZWL", name: "Zimbabwean Dollar", symbol: "Z$", rate: 14 },
  { code: "MZN", name: "Mozambican Metical", symbol: "MT", rate: 63 },
  { code: "MWK", name: "Malawian Kwacha", symbol: "MK", rate: 1730 },
  // East Africa
  { code: "TZS", name: "Tanzanian Shilling", symbol: "TSh", rate: 2650 },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh", rate: 135 },
  { code: "UGX", name: "Ugandan Shilling", symbol: "USh", rate: 3850 },
  { code: "RWF", name: "Rwandan Franc", symbol: "FRw", rate: 1280 },
  { code: "BIF", name: "Burundian Franc", symbol: "FBu", rate: 2950 },
  { code: "ETB", name: "Ethiopian Birr", symbol: "Br", rate: 57 },
  { code: "ERN", name: "Eritrean Nakfa", symbol: "Nfk", rate: 15 },
  { code: "DJF", name: "Djiboutian Franc", symbol: "Fdj", rate: 178 },
  { code: "SOS", name: "Somali Shilling", symbol: "Sh", rate: 5700 },
  { code: "SSP", name: "South Sudanese Pound", symbol: "£", rate: 1300 },
  { code: "SDG", name: "Sudanese Pound", symbol: "£", rate: 600 },
  // Central Africa
  { code: "AOA", name: "Angolan Kwanza", symbol: "Kz", rate: 850 },
  { code: "CDF", name: "Congolese Franc", symbol: "FC", rate: 2750 },
  { code: "XAF", name: "Central African CFA Franc", symbol: "FCFA", rate: 600 },
  { code: "GAB", name: "Gabonese Franc (CFA)", symbol: "FCFA", rate: 600 },
  // West Africa
  { code: "XOF", name: "West African CFA Franc", symbol: "CFA", rate: 600 },
  { code: "GHS", name: "Ghanaian Cedi", symbol: "₵", rate: 15 },
  { code: "GMD", name: "Gambian Dalasi", symbol: "D", rate: 67 },
  { code: "GNF", name: "Guinean Franc", symbol: "FG", rate: 8600 },
  { code: "LRD", name: "Liberian Dollar", symbol: "L$", rate: 190 },
  { code: "SLL", name: "Sierra Leonean Leone", symbol: "Le", rate: 23000 },
  { code: "NGN", name: "Nigerian Naira", symbol: "₦", rate: 1500 },
  { code: "MRU", name: "Mauritanian Ouguiya", symbol: "UM", rate: 40 },
  { code: "CVE", name: "Cape Verdean Escudo", symbol: "$", rate: 103 },
  { code: "STN", name: "São Tomé and Príncipe Dobra", symbol: "Db", rate: 24 },
  // North Africa
  { code: "EGP", name: "Egyptian Pound", symbol: "£E", rate: 48 },
  { code: "MAD", name: "Moroccan Dirham", symbol: "د.م.", rate: 9.95 },
  { code: "TND", name: "Tunisian Dinar", symbol: "د.ت", rate: 3.13 },
  { code: "DZD", name: "Algerian Dinar", symbol: "د.ج", rate: 134 },
  { code: "LYD", name: "Libyan Dinar", symbol: "ل.د", rate: 4.85 },
  // Indian Ocean
  { code: "KMF", name: "Comorian Franc", symbol: "CF", rate: 460 },
  { code: "SCR", name: "Seychellois Rupee", symbol: "₨", rate: 14.5 },
  { code: "MUR", name: "Mauritian Rupee", symbol: "₨", rate: 47 },
  { code: "MGA", name: "Malagasy Ariary", symbol: "Ar", rate: 4700 },
  // South America
  { code: "ARS", name: "Argentine Peso", symbol: "$", rate: 880 },
  { code: "BRL", name: "Brazilian Real", symbol: "R$", rate: 5.1 },
  { code: "CLP", name: "Chilean Peso", symbol: "$", rate: 940 },
  { code: "COP", name: "Colombian Peso", symbol: "$", rate: 4100 },
  { code: "PEN", name: "Peruvian Sol", symbol: "S/", rate: 3.75 },
  { code: "UYU", name: "Uruguayan Peso", symbol: "$U", rate: 39 },
  { code: "PYG", name: "Paraguayan Guarani", symbol: "₲", rate: 7300 },
  { code: "BOB", name: "Bolivian Boliviano", symbol: "Bs", rate: 6.9 },
  { code: "VES", name: "Venezuelan Bolívar", symbol: "Bs", rate: 36 },
  { code: "SRD", name: "Surinamese Dollar", symbol: "Sr$", rate: 38 },
  { code: "GYD", name: "Guyanese Dollar", symbol: "G$", rate: 209 },
  // Central America & Caribbean
  { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q", rate: 7.7 },
  { code: "HNL", name: "Honduran Lempira", symbol: "L", rate: 24.7 },
  { code: "NIO", name: "Nicaraguan Córdoba", symbol: "C$", rate: 36.7 },
  { code: "CRC", name: "Costa Rican Colón", symbol: "₡", rate: 520 },
  { code: "PAB", name: "Panamanian Balboa", symbol: "B/.", rate: 1 },
  { code: "DOP", name: "Dominican Peso", symbol: "RD$", rate: 58 },
  { code: "CUP", name: "Cuban Peso", symbol: "₱", rate: 240 },
  { code: "HTG", name: "Haitian Gourde", symbol: "G", rate: 132 },
  { code: "JMD", name: "Jamaican Dollar", symbol: "J$", rate: 155 },
  { code: "TTD", name: "Trinidad and Tobago Dollar", symbol: "TT$", rate: 6.78 },
  { code: "BBD", name: "Barbadian Dollar", symbol: "Bds$", rate: 2 },
  { code: "BSD", name: "Bahamian Dollar", symbol: "B$", rate: 1 },
  { code: "BZD", name: "Belize Dollar", symbol: "BZ$", rate: 2 },
  { code: "XCD", name: "East Caribbean Dollar", symbol: "EC$", rate: 2.7 },
  { code: "AWG", name: "Aruban Florin", symbol: "ƒ", rate: 1.8 },
  { code: "ANG", name: "Netherlands Antillean Guilder", symbol: "ƒ", rate: 1.8 },
  // British Overseas Territories
  { code: "KYD", name: "Cayman Islands Dollar", symbol: "CI$", rate: 0.83 },
  { code: "BMD", name: "Bermudian Dollar", symbol: "BD$", rate: 1 },
  { code: "FKP", name: "Falkland Islands Pound", symbol: "£", rate: 0.79 },
  { code: "GIP", name: "Gibraltar Pound", symbol: "£", rate: 0.79 },
  { code: "SHP", name: "Saint Helena Pound", symbol: "£", rate: 0.79 },
  // Pacific Franc & other
  { code: "XPF", name: "CFP Franc", symbol: "₣", rate: 110 },
];

// ---------------------------------------------------------------------------
// LANGUAGES — major world languages.
// code: ISO 639-1 language code
// flag: representative emoji flag for the language's primary country
// ---------------------------------------------------------------------------
export const LANGUAGES: Language[] = [
  { code: "en", name: "English", nativeName: "English", flag: "🇬🇧" },
  { code: "fr", name: "French", nativeName: "Français", flag: "🇫🇷" },
  { code: "ar", name: "Arabic", nativeName: "العربية", flag: "🇸🇦" },
  { code: "es", name: "Spanish", nativeName: "Español", flag: "🇪🇸" },
  { code: "de", name: "German", nativeName: "Deutsch", flag: "🇩🇪" },
  { code: "it", name: "Italian", nativeName: "Italiano", flag: "🇮🇹" },
  { code: "pt", name: "Portuguese", nativeName: "Português", flag: "🇵🇹" },
  { code: "zh", name: "Chinese", nativeName: "中文", flag: "🇨🇳" },
  { code: "ja", name: "Japanese", nativeName: "日本語", flag: "🇯🇵" },
  { code: "ko", name: "Korean", nativeName: "한국어", flag: "🇰🇷" },
  { code: "ru", name: "Russian", nativeName: "Русский", flag: "🇷🇺" },
  { code: "tr", name: "Turkish", nativeName: "Türkçe", flag: "🇹🇷" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", flag: "🇮🇳" },
  { code: "sw", name: "Swahili", nativeName: "Kiswahili", flag: "🇰🇪" },
  { code: "nl", name: "Dutch", nativeName: "Nederlands", flag: "🇳🇱" },
  { code: "pl", name: "Polish", nativeName: "Polski", flag: "🇵🇱" },
  { code: "sv", name: "Swedish", nativeName: "Svenska", flag: "🇸🇪" },
  { code: "no", name: "Norwegian", nativeName: "Norsk", flag: "🇳🇴" },
  { code: "da", name: "Danish", nativeName: "Dansk", flag: "🇩🇰" },
  { code: "el", name: "Greek", nativeName: "Ελληνικά", flag: "🇬🇷" },
  { code: "he", name: "Hebrew", nativeName: "עברית", flag: "🇮🇱" },
  { code: "th", name: "Thai", nativeName: "ไทย", flag: "🇹🇭" },
  { code: "vi", name: "Vietnamese", nativeName: "Tiếng Việt", flag: "🇻🇳" },
  { code: "id", name: "Indonesian", nativeName: "Bahasa Indonesia", flag: "🇮🇩" },
  { code: "ms", name: "Malay", nativeName: "Bahasa Melayu", flag: "🇲🇾" },
  { code: "fil", name: "Filipino", nativeName: "Filipino", flag: "🇵🇭" },
  { code: "fa", name: "Persian", nativeName: "فارسی", flag: "🇮🇷" },
  { code: "ur", name: "Urdu", nativeName: "اردو", flag: "🇵🇰" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", flag: "🇧🇩" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்", flag: "🇮🇳" },
];
