name: Supabase Keep Alive

on:
  schedule:
    - cron: "3,8,13,18,23,28,33,38,43,48,53,58 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Test Supabase
        run: |
          echo "Test de connexion à Supabase..."

          curl -i \
            -H "apikey: TON_ANON_KEY" \
            -H "Authorization: Bearer TON_ANON_KEY" \
            "https://wqxjsbikoriuzinordko.supabase.co/rest/v1/"
